version: '3'

services:
  wordpress:
    image: navicks/wordpress-ftp
    build:
      context: ./wordpress
      args:
        WORDPRESS_FTP_USER: ${WORDPRESS_FTP_USER}
        WORDPRESS_FTP_PASSWORD: ${WORDPRESS_FTP_PASSWORD}
    env_file: .env
    restart: always
    ports:
      - "${WORDPRESS_HTTP_PORT}:80"
      - "${WORDPRESS_HTTPS_PORT}:443"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
    volumes:
      - "${WORDPRESS_VOLUME_DIR}:/var/www/html"
    depends_on:
      - db

  db:
    image: navicks/mysql-wp
    build:
      context: ./mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${MYSQL_VOLUME_DIR}:/var/lib/mysql
